#coding: utf-8
JAVA_PROJECTS = {'hike' : {'desc' : 'HIKe Deamon',
                           'code_dir' : '/app/webapps/hike',
                           'tomcat_dir' : '/app/environment/apache-tomcat-7.0.21-deamon',
                           'source_addr' : ' http://10.168.0.101:9030/',
                           'logs_dir' : '/usr/local/hike/logs',
                           'config_dir' : '/usr/local/hike/config',
                           'host' : '10.169.0.148',
                           },
                 
                 'wechat' : {'desc' : 'HIKe 微信',
                           'code_dir' : '/app/webapps/wechat',
                           'tomcat_dir' : '/app/environment/apache-tomcat-7.0.39-wechat',
                           'source_addr' : ' http://10.168.0.101:9030/',
                           'logs_dir' : '/usr/local/hike/wechat/logs',
                           'config_dir' : '/usr/local/hike/config',
                           'host' : '10.169.0.148',
                           },

                 'listener' : {'desc' : 'HIKe 微信',
                           'code_dir' : '/app/webapps/listener',
                           'tomcat_dir' : '/app/environment/apache-tomcat-7.0.21-listener',
                           'source_addr' : ' http://10.168.0.101:9030/',
                           'logs_dir' : '/usr/local/hike/listener/logs',
                           'config_dir' : '/usr/local/hike/config',
                           'host' : '10.169.0.148',
                           },
                 
                 'admin_portal' : {'desc' : 'HIKe 微信',
                           'code_dir' : '/app/webapps/admin_portal',
                           'tomcat_dir' : '/app/environment/apache-tomcat-7.0.39',
                           'source_addr' : ' http://10.168.0.101:9030/',
                           'logs_dir' : '/usr/local/hike/admin_portal/logs',
                           'config_dir' : '/usr/local/hike/config',
                           'host' : '10.120.10.32',
                           },
                 
                 'export' : {'desc' : 'HIKe 微信',
                           'code_dir' : '/app/webapps/export',
                           'tomcat_dir' : '/app/environment/apache-tomcat-7.0.39-export',
                           'source_addr' : ' http://10.168.0.101:9030/',
                           'logs_dir' : '/usr/local/hike/export/logs',
                           'config_dir' : '/usr/local/hike/config',
                           'host' : '10.169.0.148',
                           },
                 
#                 'solr' : {'desc' : 'HIKe 微信',
#                           'code_dir' : '/app/webapps/solr',
#                           'tomcat_dir' : '/app/environment/apache-tomcat-7.0.39-solr',
#                           'source_addr' : ' http://10.168.0.101:9030/',
#                           'logs_dir' : '/usr/local/hike/wechat/logs',
#                           'config_dir' : '/usr/local/hike/config',
#                           'host' : '10.169.0.148',
#                           },
                 }

CONNECTION_INFO = {"username" : "ckt",
                   "password" : "123qwe",
                   "port" : 22,
                   }